language: node_js

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker-compose --version

script:
  - docker-compose up -d
